### ISSUE TITLE
Use Test Account for Tests

### ISSUE THREAD

**Issue by kzscisoft** [simvue-io/client#229]
Currently the refactor and functional tests do not work as they require access to a Simvue account on a server. Need to check that the token and endpoint are correct for this, and create an INI file within the CI.

@alahiff  is the token under the CI environment variables still valid?

**Comment by alahiff** [comment]
I can confirm that the CI environment variables are valid - I uploaded new ones after testing them manually. The unknown now is whether they are actually being passed into the code correctly.

**Comment by alahiff** [comment]
My original functional tests work correctly in a GitHub action. The problem is just with the "refactored" tests. Something in the tests themselves is causing the two environment variables to be redacted - `SIMVUE_URL` is being changed from `https://dev02.simvue.io` to `https://simvue.io`,  and `SIMVUE_TOKEN` is being changed to `****` I think (at least the length is being changed from 180 characters to 4).

**Comment by kzscisoft** [comment]
Turns out this was due to Poetry not keeping any externally provided environment variables. The solution was to use `export` before running the tests.
